### ISSUE TITLE
Issues on Samsung Galaxy S2

### ISSUE THREAD

**Issue by garnertb** [ROGUE-JCTD/Arbiter-Android#82]
Samsung Galaxy S2 on Android 4.0.4.  I'm not sure if we support this device this old, but if we do here are some issues:

1. When dragging the map, the screen gets selected (flashes blue like the user is selecting text on the page, not dragging a map).  Although, the application seems to function it is annoying for the user.  

2. When using the device to take a picture, the picture never shows up in Arbiter (even though it is on the device).

**Comment by ScottEvil** [comment]
Closing as will not fix
