### ISSUE TITLE
Arbiter photo load problems

### ISSUE THREAD

**Issue by danpalumbo** [ROGUE-JCTD/Arbiter-Android#95]
When selecting an exiting photo from the device library, Arbiter offers the choice from "Gallery" or "Photos". When selecting "Gallery" the user has the option to Cancel. When selecting "Photos" there is no option to cancel. Many times the device will issue an error message that Google can't handle the search and prompt the user to Abort, Retry, or Report to Google the error. This can be very frustrating because sometimes the error message occurs and sometimes not. The user should have the option to cancel the search - like it does when searching the Gallery at the very least.

**Comment by ScottEvil** [comment]
I tested this and the back button with Android satisfies this use case in both branches of this issue.
